# Generated by Django 2.2.13 on 2020-07-06 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_admin', models.CharField(max_length=20)),
                ('apellido_admin', models.CharField(max_length=20)),
                ('correo_admin', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dce', models.CharField(max_length=20)),
                ('apellido_dce', models.CharField(max_length=20)),
                ('correo_dce', models.CharField(max_length=20)),
                ('titulado', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
                ('id_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informe.Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_matricula', models.IntegerField()),
                ('rut', models.IntegerField()),
                ('nombre_est', models.CharField(max_length=20)),
                ('apellido_est', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=20)),
                ('tema', models.CharField(max_length=15)),
                ('correo_est', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('login', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
                ('id_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informe.Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_observacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(max_length=10)),
                ('id_est', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informe.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoDeTesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumario', models.CharField(max_length=10000)),
                ('introduccion', models.CharField(max_length=10000)),
                ('indice', models.CharField(max_length=10000)),
                ('texto', models.CharField(max_length=1000000)),
                ('imagen', models.ImageField(upload_to='')),
                ('conclusion', models.CharField(max_length=10000)),
                ('bibliografia', models.CharField(max_length=10000)),
                ('if_informe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informe.Informe')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=10000)),
                ('fecha_observacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(max_length=10)),
                ('id_dce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informe.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='')),
                ('detalle', models.CharField(max_length=200)),
                ('fecha_ingreso', models.DateTimeField(auto_now=True)),
                ('anexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informe.ProyectoDeTesis')),
            ],
        ),
    ]
