# Generated by Django 2.2.13 on 2020-07-10 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('informe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_capitulo', models.CharField(max_length=50)),
                ('introduccion', models.CharField(max_length=10000)),
                ('conclusion', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAsignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_autoguardado', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portada', models.CharField(max_length=1000)),
                ('sumario', models.CharField(max_length=10000)),
                ('introduccion', models.CharField(max_length=10000)),
                ('indice', models.CharField(max_length=10000)),
                ('conclusion', models.CharField(max_length=10000)),
                ('bibliografia', models.CharField(max_length=10000)),
                ('capitulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informe.Capitulo')),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informe.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parrafo', models.CharField(max_length=100000)),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informe.Imagen')),
            ],
        ),
        migrations.RemoveField(
            model_name='docente',
            name='id_admin',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='id_admin',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='id_est',
        ),
        migrations.RemoveField(
            model_name='proyectodetesis',
            name='if_informe',
        ),
        migrations.RemoveField(
            model_name='anexo',
            name='anexo',
        ),
        migrations.RemoveField(
            model_name='observacion',
            name='id_dce',
        ),
        migrations.AlterField(
            model_name='anexo',
            name='detalle',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='documento',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Informe',
        ),
        migrations.DeleteModel(
            name='ProyectoDeTesis',
        ),
        migrations.AddField(
            model_name='documento',
            name='observaciones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informe.Observacion'),
        ),
        migrations.AddField(
            model_name='detalleasignacion',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informe.Documento'),
        ),
        migrations.AddField(
            model_name='detalleasignacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capitulo',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informe.Item'),
        ),
    ]
