# Generated by Django 2.2.13 on 2020-07-10 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0002_auto_20200710_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='documento',
            new_name='campus',
        ),
        migrations.RemoveField(
            model_name='capitulo',
            name='item',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='bibliografia',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='capitulo',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='item',
            name='imagen',
        ),
        migrations.AddField(
            model_name='anexo',
            name='archivo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capitulo',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informe.Documento'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informe.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='capitulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informe.Capitulo'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informe.Documento'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informe.Documento'),
        ),
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autores', models.CharField(max_length=1000)),
                ('fechas_publicacion', models.CharField(max_length=250)),
                ('nombre_capitulo', models.CharField(max_length=700)),
                ('num_pagina_incial', models.IntegerField()),
                ('num_pagina_final', models.IntegerField()),
                ('url_recurso', models.CharField(max_length=1500)),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='informe.Documento')),
            ],
        ),
    ]
