# Generated by Django 2.2.13 on 2020-07-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0003_auto_20200710_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliografia',
            name='nombre_publicacion',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
